### PR TITLE
Feature/react tutorial

### PR DESCRIPTION
**Pull request by seperalta22**
# React Tutorial

## Summary

This branch contains the code for the Todo app we built in the React tutorial.

Some features that I have incorporated are:

- Create the application using Vite.
- Use of React Router for routing.
- Use of React Hooks.
- Create Components for Header, TodoList, TodoItem, and AddTodo.
- Handle the state of the application using the useState hook.

### CODE REVIEW

**Comment by ahmed025566** [comment]
Hello Sergio,

Although you have made a great effort in that project but there is still small touches :

- In the readme file please update npm start command to npm run preview cause you are using vite bundler in that project.

**Review by ahmed025566 — CHANGES_REQUESTED** [review]
Hello Sergio,

Although you have made a great effort in that project but there is still small touches :

- In the readme file please update npm start command to npm run preview cause you are using vite bundler in that project.

**Comment by seperalta22** [comment]
Hi @ahmed025566 !🤝  Thanks you for you code review

**Review by ahmed025566 — APPROVED** [review]
Hi Sergio, 
Every thing looks great. Your branch is ready to merge.

**Pull request merged**
